### ISSUE TITLE
MainMenu.swift not attaching menu

### ISSUE THREAD

**Issue by alicerunsonfedora** [artemis-project/swift-machine#1]
The main menu created from MainMenu.swift will run in MainWindowController.swift, but it will not attach the menu at runtime. MainMenu.swift is intended to separate the main menubar from MainWindowController.swift for clarity and design purposes, but if it cannot function properly, we'd have to opt for the chunkier MainWindowController.swift.

**Comment by alicerunsonfedora** [comment]
@Longhanks, do you know what could be going wrong here and what I can do to get Qlift to properly attach the menu?

**Comment by Longhanks** [comment]
A few things come to my mind:

1. Qlift is only an API. If you misuse Qt as an API, Qlift won't fix your code.
2. You're subclassing QMenuBar, which is fine. But your subclass has methods that depend on properties that are implicitly unwrapped optionals that are not initialized in the constructor (the menuFile QMenu which you create in MainWindowController). Why?
3. When you're already creating a subclass of QMenuBar, why does your MainWindowController have a property of type QMenuBar in addition to your subclass? Are you sure you want two menubars?
4. You're only attaching the empty QMenuBar object in MainWindowController, that's why your code isn't doing what you're expecting. See #2.

Are you sure you understand what your code is doing? This is a minor "Hello world"-level problem, that's why I could easily fix it, but once your project grows in size, I'm simply not able to take the time to read your codebase and fix your bugs. I hope you'll understand that.

I'm thankful if you find bugs in Qlift, although I have to mention again, it is only a side project of mine, I'm not guaranteeing any API stability, regular development or long term commitment.

**Comment by alicerunsonfedora** [comment]
Thanks, I think I understand how it's attaching itself now. Hopefully, I can remember this in the future when we create more apps; I've been trying to make it Xcode-like with these separate UI files to make it simpler.
