### ISSUE TITLE
Bind exitApp function to actionExit

### ISSUE THREAD

**Issue by alicerunsonfedora** [artemis-project/swift-machine#3]
The ```actionExit``` QAction should be able to be bound to the ```exitApp``` function in **Main.swift**.

- [x] Find the proper way to use Qt's QAction APIs to bind menu actions to functions
- [x] Figure out way to do so from remote **MainMenu.swift** and **MainWindowController.swift**
- [x] Bind ```exitApp()``` to ```actionExit```

**Comment by Longhanks** [comment]
Take a look: https://github.com/Longhanks/qlift-swift-example/commit/eff128675a9dae29039ebe3f3c7ba7541ec6f8f8

You needn't call libc's exit() (in your SwiftMachine.exitApp) since it's already being called with the return value of QApplication::exec() in main. You just need to tell Qt's event loop to exit, which is what QApplication::exit does.

**Comment by alicerunsonfedora** [comment]
Thanks, I have updated Swift Machine accordingly and have built in the functionality.
